name: FFMPEG STREAM
on:
  push:
    branches: [ "main" ]
jobs:
  stream:
    runs-on: ubuntu-22.04
    timeout-minutes: 420
    steps:
    - name: ffmpeg
      run: |
           sudo add-apt-repository ppa:savoury1/ffmpeg4
           sudo apt-get update -y
           sudo apt-get install -y ffmpeg python3 python3-pip wget
           sudo pip3 install requests
           wget https://raw.githubusercontent.com/Rdxcj/Test6/main/main.py
           sudo python3 main.py
